#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Armed Forces Mutual Documents - sign in'
echo '============================================================'
echo 'A normal Chromium window will open. Then:'
echo '1. Sign in to Armed Forces Mutual (do all the 2FA / verification yourself)'
echo '2. Go to your Documents / Statements area and open it'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'

"$PY" aafmaa_docs.py --open-browser $CFG
