#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Youfone Facturen - sign in'
echo '============================================================'
echo 'A normal browser window opens at https://my.youfone.nl/facturen. Then:'
echo '1. Sign in with your Youfone account. This tool never'
echo 'sees your credentials and never touches the sign-in itself'
echo '2. Confirm you can see your list of facturen'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'

"$PY" youfone_docs.py --open-browser $CFG
