#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Paylocity Pay Statements - sign in'
echo '============================================================'
echo 'A normal browser window opens at access.paylocity.com. Then:'
echo '1. Sign in the way your company does - a Paylocity username and password,'
echo 'or your company'\''s single sign-on. Either is fine: this tool never'
echo 'sees your credentials and never touches the sign-in itself'
echo '2. Complete any MFA / verification prompt yourself'

"$PY" paylocity_docs.py --open-browser $CFG
